import Sidebar from "@/components/layout/Sidebar";
import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";

const inter = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className=" px-5 lg:px-6 py-6 flex items-start gap-6">
          <Sidebar />
          <div className=" ml-0 lg:ml-28  lg:flex-1">{children}</div>
        </main>
      </body>
    </html>
  );
}
